global:
  hosts:
    domain: k8s-ingress1.lan
    gitlab:
      name: gitlab.k8s-ingress1.lan
    registry:
      name: registry.k8s-ingress1.lan
    minio:
      enabled: true
      name: minio.k8s-ingress1.lan
  
  ingress:
    configuredClass: "nginx"
    tls:
      enabled: false

nginx-ingress:
  enabled: false

gitlab:
  gitaly:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: longhorn-sc1

postgresql:
  enabled: true
  persistence:
    enabled: true
    size: 4Gi
    storageClass: longhorn-sc1

redis:
  install: true
  persistence:
    enabled: true
    size: 2Gi
    storageClass: longhorn-sc1

registry:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi
    storageClass: longhorn-sc1

minio:
  persistence:
    enabled: true
    size: 8Gi
    storageClass: longhorn-sc1

certmanager-issuer:
  email: voroninaleksandr98@gmail.com