apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: my-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging" # Указываем наш Issuer
    # nginx.ingress.kubernetes.io/rewrite-target: / # Может понадобиться для сложных приложений
spec:
  tls:
  - hosts:
    - myapp.example.com # Ваш домен
    secretName: nginx-tls-secret # Имя секрета, куда cert-manager положит сертификат
  rules:
  - host: k8s-ingress1.lan # Ваш домен
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80